# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'freeza' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for freeza
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

  target 'freezaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
